// <auto-generated />
namespace FamilyPoints.Service.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addCurrentPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCurrentPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "201306240003054_addCurrentPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
